/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OkRouteImport } from './routes/ok'
import { Route as NewContactRouteImport } from './routes/new-contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleEventsRouteImport } from './routes/console/events'
import { Route as ConsoleDeviceStatesRouteImport } from './routes/console/device-states'
import { Route as ConsoleChannelsRouteImport } from './routes/console/channels'
import { Route as ConsoleAsteriskcopyRouteImport } from './routes/console/asterisk copy'
import { Route as ConsoleAsteriskRouteImport } from './routes/console/asterisk'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OkRoute = OkRouteImport.update({
  id: '/ok',
  path: '/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const NewContactRoute = NewContactRouteImport.update({
  id: '/new-contact',
  path: '/new-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleEventsRoute = ConsoleEventsRouteImport.update({
  id: '/console/events',
  path: '/console/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleDeviceStatesRoute = ConsoleDeviceStatesRouteImport.update({
  id: '/console/device-states',
  path: '/console/device-states',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleChannelsRoute = ConsoleChannelsRouteImport.update({
  id: '/console/channels',
  path: '/console/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAsteriskcopyRoute = ConsoleAsteriskcopyRouteImport.update({
  id: '/console/asterisk copy',
  path: '/console/asterisk copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAsteriskRoute = ConsoleAsteriskRouteImport.update({
  id: '/console/asterisk',
  path: '/console/asterisk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-contact': typeof NewContactRoute
  '/ok': typeof OkRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/login': typeof AuthLoginRoute
  '/console/asterisk': typeof ConsoleAsteriskRoute
  '/console/asterisk copy': typeof ConsoleAsteriskcopyRoute
  '/console/channels': typeof ConsoleChannelsRoute
  '/console/device-states': typeof ConsoleDeviceStatesRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-contact': typeof NewContactRoute
  '/ok': typeof OkRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/login': typeof AuthLoginRoute
  '/console/asterisk': typeof ConsoleAsteriskRoute
  '/console/asterisk copy': typeof ConsoleAsteriskcopyRoute
  '/console/channels': typeof ConsoleChannelsRoute
  '/console/device-states': typeof ConsoleDeviceStatesRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-contact': typeof NewContactRoute
  '/ok': typeof OkRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/login': typeof AuthLoginRoute
  '/console/asterisk': typeof ConsoleAsteriskRoute
  '/console/asterisk copy': typeof ConsoleAsteriskcopyRoute
  '/console/channels': typeof ConsoleChannelsRoute
  '/console/device-states': typeof ConsoleDeviceStatesRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-contact'
    | '/ok'
    | '/api/events'
    | '/auth/login'
    | '/console/asterisk'
    | '/console/asterisk copy'
    | '/console/channels'
    | '/console/device-states'
    | '/console/events'
    | '/console/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-contact'
    | '/ok'
    | '/api/events'
    | '/auth/login'
    | '/console/asterisk'
    | '/console/asterisk copy'
    | '/console/channels'
    | '/console/device-states'
    | '/console/events'
    | '/console'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/new-contact'
    | '/ok'
    | '/api/events'
    | '/auth/login'
    | '/console/asterisk'
    | '/console/asterisk copy'
    | '/console/channels'
    | '/console/device-states'
    | '/console/events'
    | '/console/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewContactRoute: typeof NewContactRoute
  OkRoute: typeof OkRoute
  ApiEventsRoute: typeof ApiEventsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ConsoleAsteriskRoute: typeof ConsoleAsteriskRoute
  ConsoleAsteriskcopyRoute: typeof ConsoleAsteriskcopyRoute
  ConsoleChannelsRoute: typeof ConsoleChannelsRoute
  ConsoleDeviceStatesRoute: typeof ConsoleDeviceStatesRoute
  ConsoleEventsRoute: typeof ConsoleEventsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ok': {
      id: '/ok'
      path: '/ok'
      fullPath: '/ok'
      preLoaderRoute: typeof OkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-contact': {
      id: '/new-contact'
      path: '/new-contact'
      fullPath: '/new-contact'
      preLoaderRoute: typeof NewContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/events': {
      id: '/console/events'
      path: '/console/events'
      fullPath: '/console/events'
      preLoaderRoute: typeof ConsoleEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/device-states': {
      id: '/console/device-states'
      path: '/console/device-states'
      fullPath: '/console/device-states'
      preLoaderRoute: typeof ConsoleDeviceStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/channels': {
      id: '/console/channels'
      path: '/console/channels'
      fullPath: '/console/channels'
      preLoaderRoute: typeof ConsoleChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/asterisk copy': {
      id: '/console/asterisk copy'
      path: '/console/asterisk copy'
      fullPath: '/console/asterisk copy'
      preLoaderRoute: typeof ConsoleAsteriskcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/asterisk': {
      id: '/console/asterisk'
      path: '/console/asterisk'
      fullPath: '/console/asterisk'
      preLoaderRoute: typeof ConsoleAsteriskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewContactRoute: NewContactRoute,
  OkRoute: OkRoute,
  ApiEventsRoute: ApiEventsRoute,
  AuthLoginRoute: AuthLoginRoute,
  ConsoleAsteriskRoute: ConsoleAsteriskRoute,
  ConsoleAsteriskcopyRoute: ConsoleAsteriskcopyRoute,
  ConsoleChannelsRoute: ConsoleChannelsRoute,
  ConsoleDeviceStatesRoute: ConsoleDeviceStatesRoute,
  ConsoleEventsRoute: ConsoleEventsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
